# Generated by Django 5.2.3 on 2025-08-04 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('current_rank', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='Assistant Professor', max_length=30)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('publications', models.PositiveIntegerField(default=0)),
                ('conferences_attended', models.PositiveIntegerField(default=0)),
                ('books_published', models.PositiveIntegerField(default=0)),
                ('phd_completed', models.BooleanField(default=False)),
                ('admin_roles_held', models.PositiveIntegerField(default=0)),
                ('api_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('promotion_status', models.CharField(choices=[('Pending', 'Pending'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Promoted', 'Promoted')], default='Pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
