# Generated by Django 5.2.3 on 2025-08-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='admin_roles_held',
            new_name='admin_roles',
        ),
    ]
