# Generated by Django 5.2.3 on 2025-08-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_admin_roles_held_faculty_admin_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='admin_roles',
        ),
    ]
